"""empty message

Revision ID: 10670cf56aa9
Revises: b2ac4f548c64
Create Date: 2026-02-01 19:02:08.803155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10670cf56aa9'
down_revision = 'b2ac4f548c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
